### ISSUE TITLE
Tárgyhasználat

### ISSUE THREAD

**Issue by GubaLord** [Tmark77/Thief---Ekedition#10]
Szkript készítése, mely azért felel, hogy a játékos különféle tárgyakat használhasson.
Tartalmazzon egy listát, ami "felszerelés" típusú tárgyakat tartalmaz. (természetesen ez az osztályrendszer kialakítása után lehetséges)
Lehessen váltogatni, hogy éppen melyik tárgyat vesszük kézbe, és legyen egy "használat" gomb.

**Comment by Tmark77** [comment]
Csináljuk (Petivel)

**Comment by GubaLord** [comment]
Kész
