### ISSUE TITLE
Felkapaszkodás

### ISSUE THREAD

**Issue by GubaLord** [Tmark77/Thief---Ekedition#5]
A már implementált "objektumokra felkapaszkodás" befejezése. A feladat csupán annyi, hogy a Player ne azonnal kerüljön az objektum tetejére, hanem valamilyen folyamatosabb hatást keltő módon. Felkapaszkodás közben a játékos nem képes semmilyen egyéb cselekedet végrehajtására.

**Comment by Tmark77** [comment]
Én csinálom.
