### ISSUE TITLE
Életerő

### ISSUE THREAD

**Issue by GubaLord** [Tmark77/Thief---Ekedition#8]
A játékos tulajdonságait bővíteni kell az életerő tulajdonsággal, mely képes legyen csökkenni, és növekedni bizonyos metódusainak meghívásával. HA eléri a 0-t akkor vége a játéknak, ekkor nem mozoghatunk tovább, és kapjunk valami értesítést (egyelőre).

**Comment by nagymarton** [comment]
Elkezdtem
